- README.md
> Add Tsuru Capital

- README.md
I have used Haskell commercially with my company Reichert Brothers for almost 2 years. Haskell fits our needs extraordinarily well and we are happy to join forces. We are excited to share our success stories and knowledge about working with Haskell day-to-day.
> Add Christopher Reichert to list of individuals.

- README.md
Hello all!
I have been using Haskell professionally for the past year and a half, and Chris is an Haskell hacker playing with the language since its inception and he also wrote the original Alex (now being maintained by the great Simon Marlow).
He's our Chief Engineer here at Iris Connect, where we use Haskell both on the backend and on the frontend. Happy to be onboard!
> Added Iris me and Chris to the list

- README.md
> Add @fuzz and @gethooky

- README.md
> Add thoughtbot and Pat Brisbin

- README.md
> Added Ben Moseley.

- README.md
Signed-off-by: Neil Bartlett <njbartlett@gmail.com>
> Added Neil Bartlett

- README.md
Adding myself to the members list.
> Added Ian Graves

- README.md
> Typo fix (complimentary -> complementary)

- README.md
I'm glad you started this, and I'm excited to see where it goes!
We recently wrote about our stack at Wagon, including Haskell: <http://www.wagonhq.com/blog/engineering-at-wagon>
> Add Wagon and team members to README.md

- README.md
Thanks! Intermediate tutorial looks like a great idea!
> Added me as individual

- proposal/intermediate-haskell-documentation.md
I've got more to add about this proposal in general, but here are some things that have been at the top of my mind since the new haskell.org rollout.
> Start listing concerns for document curators

- README.md
I represent both, these are Norwegian companies (private limited stock companies). They both use Haskell in an industrial setting (Systor Vest also sponsored ICFP 2014, sponsors ICFP 2015 and the Functional Programming meetup-group in Stavanger, Norway).
> Add Systor Vest and Applikativ

- taskforce/devops.md
> Added some links and updated some descriptions.

- proposal/improved-hackage-security.md
Add freeze, replay, slowloris-for-clients and infinite-stream-of-data attacks.
Eventually we should refactor this into a threat model, followed by an enumeration of all possible attacks that this threat model allows (this has largely already been done for package managers).
> Add four known attacks to list of "current shortcomings"

- README.md
- proposal/improved-hackage-security.md
Proof reading changes only (oh, well, and I also got rid of a nastily split infinitive for you :-)
> Proof reading

- proposal/improved-hackage-security.md
I wanted to expand on what provenance should mean. I am still planning on solving  this issue soon.
> provenance back to the source repository

- README.md
Added Elsen Trading as a Haskell commercial user. ( https://github.com/elsen-trading )
> Added Elsen

- README.md
Interested in using haskell in a commercial setting.
> Request to be added to commercial haskell group.

- README.md
Reason of joining: I develop the assignment management system for the ELTE University at Budapest, a full stack web application written in Haskell, Persist, Snap and Fay. (github: andorp/bead)
> Add Andor Penzes as an individual.

- README.md
I have added [my company](http://www.1st.ug/) to the list, and added my name as well. I have been doing Haskell since about 2006, and it is also the only systems programming language used in the company since 2010. (The only other language we use is Ruby, with Rails, and even that we are in the process of abandoning by moving to either Snap or Yesod.)
> Added Scyfy (www.1st.ug) and myself.

- README.md
Add myself in the Individuals list. Denis Shevchenko.
> Adding in the Individuals list

- README.md
> Add my name and our company to the lists.

- README.md
Add the Commonwealth Bank as a commercial user of Haskell.
> Adds Commonwealth Bank

- README.md
I'm using Haskell at @assertible and @simplyrets - would love to get added to the list!
> Add Cody Reichert to Individuals section

- README.md
I want to join the commercialhaskell group.
> Requisition for membership

- README.md
ChaosGroup has two development positions + one intern position with Haskell based in Sofia, Bulgaria. 
So we would like to join the group.
> ChaosGroup is joining

- README.md
WhiteCity Code is a Romanian software development company. We use Haskell for our WhiteRCPT application.
> Adding WhiteCity Code

- README.md
Lindenbaum is a provider of telecommunications services in Germany. We use Haskell for our products.
> Add Lindenbaum

- README.md
At Fairy Tale we are currently working on some free and open source software to improve the Haskell experience and are attempting to create Safe AGI.
Example repositories:
* [Easy Haskell editor / IDE setup instructions - soon to be fully automated (WIP)](https://github.com/fairy-tale-agi-solutions/haskell-editor-setup#haskell-editor--ide-setup)
* [Haskell stack fix - fixes stack build errors automatically (WIP)](https://github.com/fairy-tale-agi-solutions/haskell-stack-fix/projects/1)
* [List of resources about artificial general intelligence](https://github.com/fairy-tale-agi-solutions/awesome-artificial-general-intelligence/blob/master/README.md#awesome-artificial-general-intelligence-)
* [Fairy Tale main repository with AGI projects](https://github.com/fairy-tale-agi-solutions/fairy-ta …
> Added the company: Fairy Tale - Artificial General Intelligence Solutions

- README.md
Add link to Keera Studios' website.
> Add link to company website.

- README.md
> Remove Least Fixed and Miëtek Bak
